# Generated by Django 3.2.7 on 2021-11-04 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='executor_id',
            new_name='executor',
        ),
    ]
