# Generated by Django 3.2.7 on 2021-11-04 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211104_1013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Label',
        ),
    ]
