# Generated by Django 3.2.7 on 2021-11-05 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_tag_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='tag',
        ),
        migrations.AddField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(to='users.Label'),
        ),
    ]
