# Generated by Django 3.2.7 on 2021-11-08 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20211105_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, to='users.Label'),
        ),
    ]
